name: Build Nuitka Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka psutil flask pillow mss toml winrt.windows.media.control nest_asyncio

      - name: Build with Nuitka
        run: |
          nuitka --standalone --onefile --output-filename=peek.exe --windows-icon-from-ico=icon.ico --enable-plugin=pylint-warnings main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: peek-exe
          path: |
            peek.exe
            main.dist/peek.exe
            main.bin.exe
            main.build/peek.exe
